#!/bin/sh
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/MyMetrixMOD/__init__.pyo
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/MyMetrixMOD/plugin.pyo
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/MyMetrixMOD
rm -rf /usr/share/enigma2/MetrixHD_MOD
rm -rf /usr/lib/enigma2/python/Components/Converter/MetrixMODChannelCryptoInfo.pyo
rm -rf /usr/lib/enigma2/python/Components/Converter/MetrixMODCaidDisplay.pyo
rm -rf /usr/lib/enigma2/python/Components/Converter/MetrixMODExtendedServiceInfo.pyo
rm -rf /usr/lib/enigma2/python/Components/Converter/MetrixMODRefString.pyo
rm -rf /usr/lib/enigma2/python/Components/Converter/MetrixMODExtendedServiceInfo.pyo
rm -rf /usr/lib/enigma2/python/Components/Renderer/MetrixMODSingleEpgList.pyo
rm -rf /usr/lib/enigma2/python/Components/Renderer/MetrixMODWeatherUpdater.pyo
rm -rf /usr/lib/enigma2/python/Components/Renderer/MetrixMODVolumeText.pyo
rm -rf /usr/lib/enigma2/python/Components/Renderer/MetrixMODXPicon.pyo
echo "                                                          "
echo "              ...Skin successful removed.                 "
echo "                                                          "