#!/bin/sh
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/MyMetrixMOD/__init__.pyo
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/MyMetrixMOD/plugin.pyo
rm -rf /usr/lib/enigma2/python/Components/Converter/ChannelCryptoInfo.pyo
rm -rf /usr/lib/enigma2/python/Components/Converter/MetrixCaidDisplay.pyo
rm -rf /usr/lib/enigma2/python/Components/Converter/MetrixExtendedServiceInfo.pyo
rm -rf /usr/lib/enigma2/python/Components/Converter/MetrixRefString.pyo
rm -rf /usr/lib/enigma2/python/Components/Converter/MetrixExtendedServiceInfo.pyo
rm -rf /usr/lib/enigma2/python/Components/Renderer/MetrixSingleEpgList.pyo
rm -rf /usr/lib/enigma2/python/Components/Renderer/MetrixWeatherUpdater.pyo
rm -rf /usr/lib/enigma2/python/Components/Renderer/MetrixVolumeText.pyo
rm -rf /usr/lib/enigma2/python/Components/Renderer/XPicon.pyo
echo "                                                          "
echo "     \  |      |     _)      |  | _ \    \  |  _ \ _ \    "
echo "    |\/ |  -_)  _|  _||\ \ / __ | |  |  |\/ | (   ||  |   "
echo "   _|  _|\___|\__|_| _| _\_\_| _|___/  _|  _|\___/___/    "
echo "                                                          "
echo "    |          _ )_)  \ |_)  __| |  /  \ |_)  __| |  |    "
echo "     _ \ |  |  _ \ | .  | | (    . <  .  | | (    __ |    "
echo "   _.__/\_, | ___/_|_|\_|_|\___|_|\_\_|\_|_|\___|_| _|    "
echo "        ___/                                              "
echo "                                                          "
echo "     The Skin MetrixHD_MOD is now being installed...      "
echo "                                                          "